import { Alert } from '../common/interfaces/alert';
import { PatientListEntity } from './interfaces/patient-list-entity.model';

export const testPatients: PatientListEntity[] = [
  {
    appointment_data: {
      appointment_datetime: '2020-09-25T09:15:00Z',
      is_telemedicine: true,
      notification_sent: false,
      telemedicine_queue_position: 1,
      telemedicine_queue_time: '2020-09-25T12:30:08.808002Z',
      telemedicine_session_status: true
    },
    appointment_datetime: '2020-09-25T09:15:00Z',
    birth_date: '1988-01-01',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Pink Eye',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-09-25T12:29:36.737317Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 158781,
    patient_name: 'LevanDrTest DEEEE',
    room: '',
    session_create: '2020-09-25T12:26:26.987847Z',
    session_key: '0239bea8-c069-42df-a8c2-f993075481f2',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: 1,
      time: '2020-09-25T12:30:08.808002Z'
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: '2020-09-25T09:15:00Z',
      is_telemedicine: true,
      notification_sent: false,
      telemedicine_queue_position: 1,
      telemedicine_queue_time: '2020-09-25T12:56:04.771578Z',
      telemedicine_session_status: true
    },
    appointment_datetime: '2020-09-25T09:15:00Z',
    birth_date: '1988-01-01',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Pink Eye',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-09-25T12:55:37.087739Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 158806,
    patient_name: 'LevanAdvinow SEEEFFF',
    room: '',
    session_create: '2020-09-25T12:53:39.452140Z',
    session_key: 'b0e7c632-4e8b-4a8c-8f5e-167fba7e83f6',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: 1,
      time: '2020-09-25T12:56:04.771578Z'
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: '2020-09-25T09:45:00Z',
      is_telemedicine: true,
      notification_sent: false,
      telemedicine_queue_position: 1,
      telemedicine_queue_time: '2020-09-25T13:13:11.584150Z',
      telemedicine_session_status: true
    },
    appointment_datetime: '2020-09-25T09:45:00Z',
    birth_date: '1993-03-03',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Pink Eye',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: '',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-09-25T13:11:18.684321Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 158823,
    patient_name: 'Update TestOne',
    room: '',
    session_create: '2020-09-25T13:07:23.331288Z',
    session_key: 'f4e8cd0d-28b6-45fd-aca6-8577fdb69b7c',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: 1,
      time: '2020-09-25T13:13:11.584150Z'
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: true,
      notification_sent: false,
      telemedicine_queue_position: 1,
      telemedicine_queue_time: '2020-09-25T13:31:32.654798Z',
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1990-09-09',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Fever',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-09-25T13:31:06.523826Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'Virtual QA-PIC-Training',
    medications: 'none',
    patient_id: 158846,
    patient_name: 'Update TestTwo',
    room: '',
    session_create: '2020-09-25T13:29:15.068035Z',
    session_key: '9fd34a37-b9cc-4fbb-a666-801f46495b5a',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: 1,
      time: '2020-09-25T13:31:32.654798Z'
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: '2020-09-25T10:30:00Z',
      is_telemedicine: true,
      notification_sent: false,
      telemedicine_queue_position: 1,
      telemedicine_queue_time: '2020-09-25T14:42:52.360878Z',
      telemedicine_session_status: true
    },
    appointment_datetime: '2020-09-25T10:30:00Z',
    birth_date: '1990-09-09',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Fever',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-09-25T14:42:20.883242Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 158891,
    patient_name: 'Test UpdateThree',
    room: '',
    session_create: '2020-09-25T14:40:52.860142Z',
    session_key: '4e82497f-e63b-48b9-9205-23cf7d73bbec',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: 1,
      time: '2020-09-25T14:42:52.360878Z'
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: '2020-09-25T11:00:00Z',
      is_telemedicine: true,
      notification_sent: false,
      telemedicine_queue_position: 1,
      telemedicine_queue_time: '2020-09-25T15:18:00.490210Z',
      telemedicine_session_status: true
    },
    appointment_datetime: '2020-09-25T11:00:00Z',
    birth_date: '1990-09-09',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Fever',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-09-25T15:17:31.144391Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 158913,
    patient_name: 'Test UpdateFour',
    room: '',
    session_create: '2020-09-25T15:15:53.566132Z',
    session_key: '6e3a37e3-c6dd-4fb0-8722-e64e05afac4b',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: 1,
      time: '2020-09-25T15:18:00.490210Z'
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: true,
      notification_sent: false,
      telemedicine_queue_position: 1,
      telemedicine_queue_time: '2020-09-25T19:04:59.304260Z',
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1988-01-01',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Pink Eye',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-09-25T19:04:35.804660Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 158986,
    patient_name: 'LevanAdvinow TestPatientEEE',
    room: '',
    session_create: '2020-09-25T19:03:27.461292Z',
    session_key: 'cf70dd69-e50a-47d2-a645-a78b69e20dae',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: 1,
      time: '2020-09-25T19:04:59.304260Z'
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1988-01-01',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Pink Eye',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-09-26T12:08:50.015728Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159033,
    patient_name: 'LevanAdvinow SunTest',
    room: '',
    session_create: '2020-09-26T12:07:00.714686Z',
    session_key: '09363433-84fb-4ffb-9f1c-dd32b69526d4',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: true,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1988-01-01',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Pink Eye',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-09-26T12:33:30.335161Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159034,
    patient_name: 'test pagejump',
    room: '',
    session_create: '2020-09-26T12:32:07.048192Z',
    session_key: '8e9e7a59-0882-4729-b8a6-7fe4fe1e41c2',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1987-01-01',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Pink Eye',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-09-29T07:08:41.230796Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159353,
    patient_name: 'LevanAdvinowEPS NormalTest',
    room: '',
    session_create: '2020-09-29T07:05:56.753779Z',
    session_key: 'b909d2ef-b6e7-49b3-8691-6b01f532f35b',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: 1,
      telemedicine_queue_time: '2020-09-29T07:52:56.904618Z',
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1993-03-03',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Sinus Infections',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: '',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-09-29T07:52:46.095266Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159355,
    patient_name: 'Almost There',
    room: '',
    session_create: '2020-09-29T07:32:41.630182Z',
    session_key: '0dbeecdd-6bf4-4888-8d29-8a66ae012ad3',
    status: 'PATIENT_WITH_DOCTOR',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: 1,
      time: '2020-09-29T07:52:56.904618Z'
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1991-01-01',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Seasonal Allergies',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-09-29T07:54:24.053982Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159357,
    patient_name: 'minhtrysecondpatient minhtry',
    room: '',
    session_create: '2020-09-29T07:51:43.921552Z',
    session_key: '5ef7ba3c-318b-4fc6-b81b-592e40b9e6af',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1988-01-01',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Pink Eye',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-09-29T10:01:20.565658Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159367,
    patient_name: 'LevanAdvinow LevanFFF',
    room: '',
    session_create: '2020-09-29T09:54:14.240075Z',
    session_key: '0121bafb-7593-414d-bb8d-b3427c226a52',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1990-06-06',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Pink Eye',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-09-29T10:22:53.477193Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159374,
    patient_name: 'test111 test222',
    room: '',
    session_create: '2020-09-29T10:21:13.651270Z',
    session_key: '43aa312c-1085-4007-8f74-37d69d0e2645',
    status: 'REGISTER',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: 1,
      telemedicine_queue_time: '2020-09-29T10:35:47.765935Z',
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1990-06-06',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Pink Eye',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: '',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-09-29T10:33:58.661744Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159379,
    patient_name: 'Test21 tewet',
    room: '',
    session_create: '2020-09-29T10:32:45.712675Z',
    session_key: 'beb3ba8f-e207-4210-986d-18c5a7815045',
    status: 'PATIENT_WAITING',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: 1,
      time: '2020-09-29T10:35:47.765935Z'
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1991-01-01',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Seasonal Allergies',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-09-29T11:27:05.983474Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159385,
    patient_name: 'nhimtrythridpatient switchdev',
    room: '',
    session_create: '2020-09-29T11:23:59.214466Z',
    session_key: '2f752e75-9f37-4fcf-9d70-d8017b96fdd4',
    status: 'PATIENT_WAITING_TELEMEDICINE',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1991-01-01',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Seasonal Allergies',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-09-29T11:37:15.426666Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159388,
    patient_name: 'nhimtrydevforthpatient switchdev',
    room: '',
    session_create: '2020-09-29T11:33:21.986637Z',
    session_key: '7fd2e9e1-4b96-4202-9d9f-99ea2ff0946b',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1991-01-01',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Seasonal Allergies',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: '',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-09-29T11:58:37.007585Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159391,
    patient_name: 'nhimtryswitch switchpractice',
    room: '',
    session_create: '2020-09-29T11:55:08.412617Z',
    session_key: '85490309-d0d9-453a-a4fe-23621d7197c1',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: 1,
      telemedicine_queue_time: '2020-09-29T12:05:22.586329Z',
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1991-01-01',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Seasonal Allergies',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-09-29T12:05:01.411102Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159394,
    patient_name: 'nhimtryswitchclinic switchpractice',
    room: '',
    session_create: '2020-09-29T12:02:56.971819Z',
    session_key: 'adf9f216-4bc6-4b32-8f33-18ed05675bd5',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: 1,
      time: '2020-09-29T12:05:22.586329Z'
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1990-12-11',
    clerk_id: 123321,
    clerk_name: 'CLERK',
    covid_19_possible: false,
    detail_visit_reason: 'Cough',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: '',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-09-29T12:06:26.486414Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159393,
    patient_name: 'Test111 Test2222',
    room: '',
    session_create: '2020-09-29T12:02:32.827365Z',
    session_key: '71707e2f-7537-4325-9816-9f517a7d3ba0',
    status: 'PATIENT_WITH_DOCTOR',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1990-06-06',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Cough',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-09-29T13:21:50.379494Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159414,
    patient_name: 'sdfsdf dfgdfgdfg',
    room: '',
    session_create: '2020-09-29T13:20:21.834786Z',
    session_key: '97bfd55c-1005-4f41-b871-8d17af7ca621',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1991-01-01',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Wellness Check',
    doctor_id: 820,
    doctor_name: 'Adelina PIC',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-01T09:40:04.556932Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159778,
    patient_name: 'dev minhfirsttry',
    room: '',
    session_create: '2020-10-01T09:36:02.105528Z',
    session_key: '467c1ecb-f480-4126-a9c7-c09aeeef1d4d',
    status: 'TREATMENT_COMPLETE',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: '2020-10-01T10:12:10.042879Z',
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1990-09-09',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Sinus Infections',
    doctor_id: 820,
    doctor_name: 'Adelina PIC',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-01T10:29:29.959495Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159783,
    patient_name: 'TestNew EPSLevelOne',
    room: '',
    session_create: '2020-10-01T10:27:19.604103Z',
    session_key: 'acca11fd-9eae-4025-b6ff-db28591ef8df',
    status: 'TREATMENT_COMPLETE',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: '2020-10-01T10:57:55.227204Z',
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1988-01-01',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Pink Eye',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: null,
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159792,
    patient_name: 'LevanAdvinow EPSTEST',
    room: '',
    session_create: '2020-10-01T11:02:26.602552Z',
    session_key: 'd1f3e581-4e20-46e2-b6fd-45f92b296a59',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1988-01-01',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Pink Eye',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-01T11:19:48.877780Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159798,
    patient_name: 'LevanAdvinow EPSFFFFF',
    room: '',
    session_create: '2020-10-01T11:18:40.721427Z',
    session_key: '4d2183b6-8225-437a-bd7b-49a6f7e760a8',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1988-01-01',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Pink Eye',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-01T11:49:34.444195Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159806,
    patient_name: 'LevanAdvinowDFD EEEEEE',
    room: '',
    session_create: '2020-10-01T11:48:26.590519Z',
    session_key: 'f2fd51ff-7a1c-4a15-93a0-fc8be7ec8445',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1990-09-09',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'UTI',
    doctor_id: 820,
    doctor_name: 'Adelina PIC',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-01T12:33:34.892465Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159812,
    patient_name: 'TestQA PartialOne',
    room: '',
    session_create: '2020-10-01T12:29:56.322997Z',
    session_key: 'e29204ce-6609-4b68-9701-3c2503cdaf1a',
    status: 'TREATMENT_COMPLETE',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: '2020-10-01T13:48:51.160027Z',
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1987-11-11',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Cough',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: '',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-01T14:13:40.808895Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159836,
    patient_name: 'ivan ivan',
    room: '',
    session_create: '2020-10-01T14:12:11.407078Z',
    session_key: '85dd4659-9641-4028-a324-636008d5dad1',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1990-09-09',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Pink Eye',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: '',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-01T15:11:03.548537Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159843,
    patient_name: 'Test PartialTwo',
    room: '',
    session_create: '2020-10-01T15:04:01.774074Z',
    session_key: '1294d424-6f34-48a4-ba74-18438f1491d7',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: '2020-10-01T14:00:00Z',
      is_telemedicine: true,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: '2020-10-01T14:00:00Z',
    birth_date: '1987-11-11',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Cough',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: '',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-01T16:00:12.381158Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159847,
    patient_name: 'ivan ivan',
    room: '',
    session_create: '2020-10-01T15:58:48.288668Z',
    session_key: '9e3aefb5-45b6-4e51-bd44-7fcc54eb794f',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: '2020-10-01T13:15:00Z',
      is_telemedicine: true,
      notification_sent: false,
      telemedicine_queue_position: 1,
      telemedicine_queue_time: '2020-10-01T16:12:13.482859Z',
      telemedicine_session_status: true
    },
    appointment_datetime: '2020-10-01T13:15:00Z',
    birth_date: '1987-11-11',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Cough',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-01T16:11:56.763222Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159848,
    patient_name: 'ivan ivan',
    room: '',
    session_create: '2020-10-01T16:10:43.525996Z',
    session_key: 'c9e239c8-ed85-4dd8-a6b7-3179f7002759',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: 1,
      time: '2020-10-01T16:12:13.482859Z'
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: '2020-10-01T14:15:00Z',
      is_telemedicine: true,
      notification_sent: false,
      telemedicine_queue_position: 1,
      telemedicine_queue_time: '2020-10-01T17:02:00.957919Z',
      telemedicine_session_status: true
    },
    appointment_datetime: '2020-10-01T14:15:00Z',
    birth_date: '1987-11-11',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Cough',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: '',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-01T17:01:41.500239Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159850,
    patient_name: 'ivan timeout',
    room: '',
    session_create: '2020-10-01T17:00:17.076830Z',
    session_key: '52ef1479-72d3-4850-92a1-afe1915bb713',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: 1,
      time: '2020-10-01T17:02:00.957919Z'
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: '2020-10-01T14:00:00Z',
      is_telemedicine: true,
      notification_sent: false,
      telemedicine_queue_position: 1,
      telemedicine_queue_time: '2020-10-01T17:17:31.241865Z',
      telemedicine_session_status: true
    },
    appointment_datetime: '2020-10-01T14:00:00Z',
    birth_date: '1987-11-11',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Cough',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: '',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-01T17:17:14.523908Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159853,
    patient_name: 'ivan connect',
    room: '',
    session_create: '2020-10-01T17:15:52.985377Z',
    session_key: 'd26b8e7e-d0cd-47e9-8219-b4bd56104893',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: 1,
      time: '2020-10-01T17:17:31.241865Z'
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: '2020-10-02T09:30:00Z',
      is_telemedicine: true,
      notification_sent: false,
      telemedicine_queue_position: 1,
      telemedicine_queue_time: '2020-10-01T17:30:21.357907Z',
      telemedicine_session_status: true
    },
    appointment_datetime: '2020-10-02T09:30:00Z',
    birth_date: '1987-11-11',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Cough',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: '',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-01T17:30:03.462957Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159854,
    patient_name: 'ivan newone',
    room: '',
    session_create: '2020-10-01T17:28:38.146194Z',
    session_key: '20f36530-bce6-47c4-92bf-3d7631a6979d',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: 1,
      time: '2020-10-01T17:30:21.357907Z'
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: '2020-10-02T15:00:00Z',
      is_telemedicine: true,
      notification_sent: false,
      telemedicine_queue_position: 1,
      telemedicine_queue_time: '2020-10-01T17:51:21.953651Z',
      telemedicine_session_status: true
    },
    appointment_datetime: '2020-10-02T15:00:00Z',
    birth_date: '1987-11-11',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Cough',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: '',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-01T17:51:02.224746Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159859,
    patient_name: 'oleja ajelo',
    room: '',
    session_create: '2020-10-01T17:49:15.321424Z',
    session_key: '7038acd1-9ad0-4256-be69-6f6d83ade33c',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: 1,
      time: '2020-10-01T17:51:21.953651Z'
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: true,
      notification_sent: false,
      telemedicine_queue_position: 1,
      telemedicine_queue_time: '2020-10-01T18:13:19.010944Z',
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1986-06-06',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Pink Eye',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-01T18:12:59.101510Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159860,
    patient_name: 'Dev ReleaseKiosk',
    room: '',
    session_create: '2020-10-01T18:01:49.430110Z',
    session_key: '67daf7a9-ae20-4d68-8a10-e73912ff272d',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: 1,
      time: '2020-10-01T18:13:19.010944Z'
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: true,
      notification_sent: false,
      telemedicine_queue_position: 1,
      telemedicine_queue_time: '2020-10-01T18:28:14.554875Z',
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1986-06-06',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Pink Eye',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: '',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-01T18:28:05.996912Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159868,
    patient_name: 'Dev NoInsurance',
    room: '',
    session_create: '2020-10-01T18:25:49.531619Z',
    session_key: '84440840-4e03-479c-8ca9-096836501d74',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: 1,
      time: '2020-10-01T18:28:14.554875Z'
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: true,
      notification_sent: false,
      telemedicine_queue_position: 1,
      telemedicine_queue_time: '2020-10-01T18:44:53.054622Z',
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1988-06-06',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Pink Eye',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: '',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-01T18:44:44.630161Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159871,
    patient_name: 'Dev ePresribeHoubolt',
    room: '',
    session_create: '2020-10-01T18:41:08.314418Z',
    session_key: '33f2afb7-400f-4b29-a2b7-00283e776403',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: 1,
      time: '2020-10-01T18:44:53.054622Z'
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: true,
      notification_sent: false,
      telemedicine_queue_position: 1,
      telemedicine_queue_time: '2020-10-01T19:08:08.034776Z',
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1986-06-06',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Pink Eye',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: '',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-01T19:08:00.218565Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159883,
    patient_name: 'Dev EpsOne',
    room: '',
    session_create: '2020-10-01T19:05:17.219297Z',
    session_key: '92d88dab-a7ba-4750-bad9-ffe5bccd9e9b',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: 1,
      time: '2020-10-01T19:08:08.034776Z'
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: '2020-10-02T14:00:00Z',
      is_telemedicine: true,
      notification_sent: false,
      telemedicine_queue_position: 1,
      telemedicine_queue_time: '2020-10-01T20:08:08.219369Z',
      telemedicine_session_status: true
    },
    appointment_datetime: '2020-10-02T14:00:00Z',
    birth_date: '1987-11-11',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Cough',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: '',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-01T20:07:50.803448Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159900,
    patient_name: 'ivan ivan',
    room: '',
    session_create: '2020-10-01T20:05:40.454052Z',
    session_key: '3efbd7ed-1ec9-4777-a1f5-3b9ae5f60297',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: 1,
      time: '2020-10-01T20:08:08.219369Z'
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1991-01-01',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Seasonal Allergies',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: 'PATIENT_STARTED',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-02T04:22:53.648875Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159915,
    patient_name: 'dev advinowfirstfirst',
    room: '',
    session_create: '2020-10-02T04:19:21.867469Z',
    session_key: '8a39559c-7508-44af-b211-d9eec872b974',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1991-01-01',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Seasonal Allergies',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: '',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-02T04:49:47.190618Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159916,
    patient_name: 'dev advinowminhsecondsecond',
    room: '',
    session_create: '2020-10-02T04:48:16.930173Z',
    session_key: '77bba514-4bca-4b3c-a426-322c6c27c46f',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1991-01-01',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Seasonal Allergies',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: '',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-02T04:58:08.242942Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159917,
    patient_name: 'dev advinowminhtrythirdthird',
    room: '',
    session_create: '2020-10-02T04:56:48.810182Z',
    session_key: '792b0b6e-993f-44ea-997c-d2f720f3a9f2',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1991-01-01',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Seasonal Allergies',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: '',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-02T06:15:34.472062Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159918,
    patient_name: 'dev advinowminhtryfourth',
    room: '',
    session_create: '2020-10-02T06:11:01.916502Z',
    session_key: 'c51ab7e6-5e3f-400f-8335-c917841a5599',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1991-01-01',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Seasonal Allergies',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: '',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-02T07:05:19.805953Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159919,
    patient_name: 'dev adviondevfirst',
    room: '',
    session_create: '2020-10-02T07:03:00.340520Z',
    session_key: 'e7ec2ff7-ee8a-4426-b511-0eb6e7442e9b',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  },
  {
    appointment_data: {
      appointment_datetime: null,
      is_telemedicine: false,
      notification_sent: false,
      telemedicine_queue_position: null,
      telemedicine_queue_time: null,
      telemedicine_session_status: true
    },
    appointment_datetime: null,
    birth_date: '1990-09-09',
    clerk_id: 0,
    clerk_name: '',
    covid_19_possible: false,
    detail_visit_reason: 'Sinus Infections',
    doctor_id: 0,
    doctor_name: '',
    edb_final: false,
    edb_state: '',
    ehr_success: false,
    gender: 'MALE',
    injections: 'none',
    is_virtual_doctor: false,
    kiosk: 'QAPICPartial1',
    kiosk_complete: '2020-10-02T08:25:04.010127Z',
    labs: 'none',
    location_id: 16693,
    location_name: 'QA-PIC-Training Virtual',
    medications: 'none',
    patient_id: 159921,
    patient_name: 'TestEPS EPSLevelTwo',
    room: '',
    session_create: '2020-10-02T08:13:21.620220Z',
    session_key: 'f7407535-339c-4650-83a8-3d6b97d81ae3',
    status: 'REGISTERED',
    telemedecine_url: '',
    telemedicine_mode: 'ADVINOW',
    telemedicine_queue: {
      place: null,
      time: null
    },
    treatment_complete: null,
    vitals: 'none'
  }
] as unknown as PatientListEntity[];

export const alerts: Alert[] = [
  {
    code: 'labsOrdered',
    patient: 159792,
    target: 'MA',
    message: '',
    id: 1
  },
  {
    code: 'injectionsOrdered',
    patient: 159792,
    target: 'MA',
    message: '',
    id: 2
  },
  {
    code: 'medicationsOrdered',
    patient: 159792,
    target: 'MA',
    message: '',
    id: 3
  },
  {
    code: 'chestPain',
    patient: 159792,
    target: 'ANY',
    message: 'Patient experiencing chest pain.',
    id: 4
  },
  {
    code: 'breathDifficulties',
    patient: 159812,
    target: 'Provider',
    message: 'Patient experiencing breathing difficulties,',
    id: 5
  }
];
