export enum SymptomTypesEnum {
  'BASIC' = 'basic',
  'DESCRIPTION' = 'description',
  'FLUIDS' = 'fluids description',
  'VOLUMES' = 'fluids volume',
  'TEXTURE' = 'texture',
  'SCALE' = 'scale',
  'PAIN_SWELLING_GROUP' = 'Pain/Swelling',
  'COUGH' = 'cough',
  'MADE_BETTER_BY' = 'relieved by',
  'MADE_WORSE_BY' = 'made worse by',
  'ASSOCIATED_WITH' = 'stance associated',
  'OCCURS' = 'time associated',
  'MOVEMENT' = 'movement',
  'PS_LOCATION' = 'location',
  'STARTED_HERE' = 'started here',
  'CURRENT_DISTRIBUTION' = 'current rash distribution',
  'DISTRIBUTION_PATTERN' = 'distribution pattern',
  'SOLES_AND_FEET' = 'palm and sole',
  'RASH_CHANGE' = 'change in rash',
  'RASH_SIZE' = 'change in rash size',
  'RASH' = 'rash',
  'DESCRIBED_AS' = 'rash description'
}
