export const units = [
  { value: 'Pills', label: 'Pills' },
  { value: 'G', label: 'G' },
  { value: 'MG', label: 'MG' },
  { value: 'ML', label: 'ML' },
  { value: 'MCG', label: 'MCG' },
  { value: 'MG/ML', label: 'MG/ML' }
];

export const routes = [
  { value: 'ORAL', label: 'Oral' },
  { value: 'NASAL', label: 'Nasal' },
  { value: 'INHALATION', label: 'Inhalation' },
  { value: 'INJECTION', label: 'Injection' },
  { value: 'INTRAVENOUS', label: 'Intravenous' },
  { value: 'MISCELLANEOUS', label: 'Miscellaneous' },
  { value: 'INTRATHECAL', label: 'Intrathecal' }
];

export const PVForms = [
  { value: 'application', label: 'application' },
  { value: 'capsule', label: 'capsule' },
  { value: 'drop', label: 'drop' },
  { value: 'gm', label: 'gm' },
  { value: 'item', label: 'item' },
  { value: 'lozenge', label: 'lozenge' },
  { value: 'mcg', label: 'mcg' },
  { value: 'mg', label: 'mg' },
  { value: 'mL', label: 'mL' },
  { value: 'package', label: 'package' },
  { value: 'patch', label: 'patch' },
  { value: 'pill', label: 'pill' },
  { value: 'puff', label: 'puff' },
  { value: 'scoop', label: 'scoop' },
  { value: 'squirt', label: 'squirt' },
  { value: 'suppository', label: 'suppository' },
  { value: 'syringe', label: 'syringe' },
  { value: 'tablet', label: 'tablet' },
  { value: 'troche', label: 'troche' },
  { value: 'unit', label: 'unit' }
];

export const PVRoutes = [
  {value: 'by mouth', label: 'by mouth'},
  {value: 'ears, both', label: 'ears, both'},
  {value: 'ear, left', label: 'ear, left'},
  {value: 'ear, right', label: 'ear, right'},
  {value: 'eyes, both', label: 'eyes, both'},
  {value: 'eye, left', label: 'eye, left'},
  {value: 'eye, right', label: 'eye, right'},
  {value: 'eyelids, apply to', label: 'eyelids, apply to'},
  {value: 'eye, surgical', label: 'eye, surgical'},
  {value: 'face, apply to', label: 'face, apply to'},
  {value: 'face, thin layer to', label: 'face, thin layer to'},
  {value: 'feeding tube, via', label: 'feeding tube, via'},
  {value: 'inhale', label: 'inhale'},
  {value: 'inject, intramuscular', label: 'inject, intramuscular'},
  {value: 'intravenous', label: 'intravenous'},
  {value: 'lip, under the', label: 'lip, under the'},
  {value: 'nail, apply to', label: 'nail, apply to'},
  {value: 'sinuses, in the', label: 'sinuses, in the'},
  {value: 'penis, inject into', label: 'penis, inject into'},
  {value: 'rectum, in the', label: 'rectum, in the'},
  {value: 'scalp, apply to', label: 'scalp, apply to'},
  {value: 'skin, inject below', label: 'skin, inject below'},
  {value: 'skin, inject into', label: 'skin, inject into'},
  {value: 'skin, apply on', label: 'skin, apply on'},
  {value: 'teeth, apply to', label: 'teeth, apply to'},
  {value: 'tongue, on the', label: 'tongue, on the'},
  {value: 'tongue, under the', label: 'tongue, under the'},
  {value: 'urethra, in the', label: 'urethra, in the'},
  {value: 'vagina, in the', label: 'vagina, in the'},
  {value: 'epidural', label: 'epidural'},
  {value: 'in vitro', label: 'in vitro'},
  {value: 'intraarterial', label: 'intraarterial'},
  {value: 'intraarticular', label: 'intraarticular'},
  {value: 'intraocular', label: 'intraocular'},
  {value: 'intraperitoneal', label: 'intraperitoneal'},
  {value: 'intrapleural', label: 'intrapleural'},
  {value: 'intrathecal', label: 'intrathecal'},
  {value: 'intrauterine', label: 'intrauterine'},
  {value: 'intravesical', label: 'intravesical'},
  {value: 'perfusion', label: 'perfusion'},
  {value: 'rinse', label: 'rinse'}
];

export const PVAmount = [
  {value: '1', label: '1'},
  {value: '1-2', label: '1-2'},
  {value: '1-3', label: '1-3'},
  {value: '2-3', label: '2-3'},
  {value: '0.33/third', label: '0.33/third'},
  {value: '0.5/half', label: '0.5/half'},
  {value: '0.5-1', label: '0.5-1'},
  {value: '1.5', label: '1.5'},
  {value: '2', label: '2'},
  {value: '2.5', label: '2.5'},
  {value: '3', label: '3'},
  {value: '4', label: '4'},
  {value: '5', label: '5'},
  {value: '6', label: '6'},
  {value: '7', label: '7'},
  {value: '8', label: '8'},
  {value: '9', label: '9'},
  {value: '10', label: '10'}
];

export const PVDispenseForm = [
  {value: 'Not Specified', label: 'Not Specified'},
  {value: 'Ampoule', label: 'Ampoule'},
  {value: 'Bag', label: 'Bag'},
  {value: 'Bottle', label: 'Bottle'},
  {value: 'Box', label: 'Box'},
  {value: 'Capsule', label: 'Capsule'},
  {value: 'Cartridge', label: 'Cartridge'},
  {value: 'Container', label: 'Container'},
  {value: 'Drop', label: 'Drop'},
  {value: 'Each', label: 'Each'},
  {value: 'Fluid Ounce', label: 'Fluid Ounce'},
  {value: 'Gram', label: 'Gram'},
  {value: 'Gum', label: 'Gum'},
  {value: 'Inhaler', label: 'Inhaler'},
  {value: 'International Unit', label: 'International Unit'},
  {value: 'Kit', label: 'Kit'},
  {value: 'Liter', label: 'Liter'},
  {value: 'Lozenge', label: 'Lozenge'},
  {value: 'Milligram', label: 'Milligram'},
  {value: 'Million Units', label: 'Million Units'},
  {value: 'Mutually Defined', label: 'Mutually Defined'},
  {value: 'Pack', label: 'Pack'},
  {value: 'Packet', label: 'Packet'},
  {value: 'Pen', label: 'Pen'},
  {value: 'Pint', label: 'Pint'},
  {value: 'Strip', label: 'Strip'},
  {value: 'Suppository', label: 'Suppository'},
  {value: 'Syringe', label: 'Syringe'},
  {value: 'Tablespoon', label: 'Tablespoon'},
  {value: 'Transdermal Patch', label: 'Transdermal Patch'},
  {value: 'Tube', label: 'Tube'},
  {value: 'Unit', label: 'Unit'},
  {value: 'Vial', label: 'Vial'}
];

export const PVFrequency = [
  { option: 'Daily', readableText: 'Daily', doseValue: 1 },
  { option: 'QOD', readableText: 'Every other day', doseValue: 0.5 },
  { option: 'BID', readableText: 'Twice a day', doseValue: 2 },
  { option: 'TID', readableText: 'Three times a day', doseValue: 3 },
  { option: 'QID', readableText: 'Four times a day', doseValue: 4 },
  { option: 'QAM', readableText: 'Every morning', doseValue: 1 },
  { option: 'HS', readableText: 'At bedtime', doseValue: 1 },
  { option: 'Q2H', readableText: 'Every 2 hours', doseValue: 12 },
  { option: 'Q4H', readableText: 'Every 4 hours', doseValue: 6 },
  { option: 'Q6H', readableText: 'Every 8 hours', doseValue: 4 },
  { option: 'Q8H', readableText: 'Every 8 hours', doseValue: 3 },
  { option: 'Q12H', readableText: 'Every 12 hours', doseValue: 2 },
  { option: 'Q24H', readableText: 'Every 24 hours', doseValue: 1 },
  { option: 'QWK', readableText: 'Every week', doseValue: 0.1429 },
  { option: 'PRN', readableText: 'As needed', doseValue: 0 }
];
